version: "3"

services:
  webservice:
    container_name: hor-configurator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - web

networks:
  web:
    external: false

